'use client';
import React,{useEffect,useMemo,useState}from'react';
type Contact={id:string;contact_type:string;value:string;verified_at?:string|null};
type Institution={id:string;name:string;type:string;wilaya:string|null;parent_institution_id:string|null;address:string|null;website:string|null;email:string|null;notes:string|null;contacts:Contact[];verified_at?:string|null};
const WA='213558357689';
const LABEL:any={council:'مجلس قضاء',court:'محكمة',administrative_court:'محكمة إدارية',administrative_appellate_court:'محكمة إدارية للاستئناف',commercial_court:'محكمة تجارية متخصصة',supreme_court:'المحكمة العليا',state_council:'مجلس الدولة'};
const msg=(s:string)=>'https://wa.me/'+WA+'?text='+encodeURIComponent(s);
const byName=(a:Institution,b:Institution)=>a.name.localeCompare(b.name,'ar');
export default function JudicialInstitutionsInfo(){
 const [items,setItems]=useState<Institution[]>([]),[q,setQ]=useState(''),[admin,setAdmin]=useState(false),[login,setLogin]=useState(false),[pass,setPass]=useState(''),[err,setErr]=useState(''),[edit,setEdit]=useState<any>(null),[phone,setPhone]=useState<any>(null),[open,setOpen]=useState<Record<string,boolean>>({});
 const load=async()=>{const r=await fetch('/api/judicial-institutions',{cache:'no-store'});const j=await r.json();setItems(j.data||[])};
 useEffect(()=>{load();fetch('/api/admin/session').then(r=>r.json()).then(j=>setAdmin(!!j.authenticated)).catch(()=>{})},[]);
 const filtered=useMemo(()=>{const n=q.trim().toLocaleLowerCase('ar');return n?items.filter(i=>(i.name+' '+(i.wilaya||'')+' '+LABEL[i.type]+' '+i.contacts.map(c=>c.value).join(' ')).toLocaleLowerCase('ar').includes(n)):items},[items,q]);
 const councils=filtered.filter(i=>i.type==='council').sort(byName);
 const courtsBy=(id:string)=>filtered.filter(i=>i.type==='court'&&i.parent_institution_id===id).sort(byName);
 const apps=filtered.filter(i=>i.type==='administrative_appellate_court').sort(byName);
 const adminCourts=filtered.filter(i=>i.type==='administrative_court').sort((a,b)=>(a.wilaya||a.name).localeCompare(b.wilaya||b.name,'ar'));
 const commercial=filtered.filter(i=>i.type==='commercial_court').sort(byName);
 const supreme=filtered.filter(i=>i.type==='supreme_court');
 const state=filtered.filter(i=>i.type==='state_council');
 const loginAdmin=async()=>{const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:pass})});if(!r.ok){setErr('كلمة السر غير صحيحة');return}setAdmin(true);setLogin(false);setPass('');setErr('')};
 const saveI=async()=>{const r=await fetch('/api/admin/judicial-institution',{method:edit.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(edit)});if(!r.ok){alert('تعذر حفظ الهيئة');return}setEdit(null);load()};
 const saveP=async()=>{const url=phone.id?'/api/admin/judicial-contact':'/api/admin/judicial-contacts';const body=phone.id?{contactId:phone.id,value:phone.value}:{institutionId:phone.institutionId,value:phone.value,contactType:'lawyer_delegation_phone',label:'رقم هاتف المندوبية'};const r=await fetch(url,{method:phone.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok){alert('تعذر حفظ الرقم');return}setPhone(null);load()};
 const toggle=(id:string)=>setOpen(v=>({...v,[id]:!v[id]}));
 const Card=({i,compact=false}:{i:Institution;compact?:boolean})=>{const ps=i.contacts.filter(c=>c.contact_type.startsWith('lawyer_delegation'));return <div className={`rounded-2xl border bg-white dark:bg-gray-900 ${compact?'p-3':'p-4'} shadow-sm`}><div className="flex items-start justify-between gap-2"><div><b className="text-sm">{compact?'⚖️':'🏛️'} {i.name}</b><div className="mt-1 text-xs text-gray-500">{i.wilaya&&`ولاية ${i.wilaya} · `}{LABEL[i.type]}</div></div>{admin&&<button onClick={()=>setEdit({...i,parentId:i.parent_institution_id||''})} className="rounded-xl border px-2.5 py-1.5 text-xs text-blue-700">✏️ تعديل</button>}</div><div className="mt-3 rounded-xl bg-gray-50 dark:bg-gray-800/60 p-3"><div className="text-xs font-black text-gray-500">📞 رقم هاتف المندوبية</div>{ps.length?ps.map(c=><div key={c.id} className="mt-2 flex items-center justify-between gap-2"><a dir="ltr" href={'tel:'+c.value} className="font-black text-green-700">{c.value}</a>{admin&&<span className="flex gap-1"><button onClick={()=>setPhone({id:c.id,value:c.value})} className="rounded-lg px-2">✏️</button><button onClick={async()=>{if(confirm('حذف رقم المندوبية؟')){await fetch('/api/admin/judicial-contacts',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({contactId:c.id})});load()}}} className="rounded-lg px-2">🗑️</button></span>}</div>):<div className="mt-2 flex flex-wrap items-center justify-between gap-2"><span className="text-xs font-bold text-amber-700">⚠️ لا يوجد رقم مندوبية مسجل.</span><a target="_blank" rel="noreferrer" className="rounded-xl bg-green-600 px-3 py-2 text-xs font-black text-white" href={msg('لدي رقم مندوبية المحامين الخاصة بـ '+i.name+' وأرغب في إضافته إلى الدليل.')}>📲 ساهم بالرقم</a></div>}{admin&&<button onClick={()=>setPhone({institutionId:i.id,value:''})} className="mt-2 rounded-xl bg-blue-50 px-3 py-1.5 text-xs text-blue-700">➕ إضافة رقم المندوبية</button>}</div><div className="mt-3 grid gap-2 sm:grid-cols-2 text-xs"><div>✉️ {i.email||'البريد غير متوفر'}</div><div>📍 {i.address||'العنوان غير متوفر'}</div></div>{i.website&&<a href={i.website} target="_blank" rel="noreferrer" className="mt-2 inline-block text-xs font-bold text-blue-700">🌐 الموقع الرسمي</a>}<a target="_blank" rel="noreferrer" className="mt-3 inline-flex rounded-xl bg-green-600 px-3 py-2 text-xs font-black text-white" href={msg('أبلغ عن خطأ أو أريد تحديث معلومات مندوبية المحامين الخاصة بـ '+i.name)}>📲 إبلاغ عن خطأ / تحديث</a></div>};
 const Council=({c}:{c:Institution})=>{const kids=courtsBy(c.id),is=open[c.id];return <div className="rounded-2xl border bg-white dark:bg-gray-900 overflow-hidden shadow-sm"><button onClick={()=>toggle(c.id)} className="w-full flex items-center justify-between p-4 text-right hover:bg-gray-50 dark:hover:bg-gray-800"><span><b>⚖️ {c.name}</b><span className="mr-2 text-xs text-gray-500">{kids.length} محكمة</span></span><span className="text-lg">{is?'⌃':'⌄'}</span></button>{is&&<div className="border-t p-3 space-y-2 bg-gray-50/70 dark:bg-gray-950/30"><Card i={c}/>{kids.length?<div className="grid gap-2 md:grid-cols-2">{kids.map(k=><Card key={k.id} i={k} compact/>)}</div>:<div className="p-4 text-xs text-gray-500">لا توجد محاكم مرتبطة بهذا المجلس في قاعدة البيانات حاليًا.</div>}</div>}</div>};
 const Section=({title,icon,count,children}:{title:string;icon:string;count?:number;children:React.ReactNode})=><section className="rounded-3xl border bg-gray-50/70 dark:bg-gray-950/20 p-4"><div className="mb-4 flex items-center justify-between"><h3 className="text-base font-black">{icon} {title}</h3>{count!==undefined&&<span className="rounded-full bg-white px-3 py-1 text-xs font-bold shadow-sm dark:bg-gray-900">{count}</span>}</div>{children}</section>;
 const AdminCourts=()=>{const grouped=adminCourts.reduce<Record<string,Institution[]>>((acc,c)=>{const key=c.wilaya||'غير محددة';(acc[key]??=[]).push(c);return acc},{});const groups=Object.entries(grouped).sort((a,b)=>a[0].localeCompare(b[0],'ar'));return <div className="space-y-2">{groups.map(([wilaya,courts])=><div key={wilaya} className="rounded-2xl border bg-white dark:bg-gray-900 overflow-hidden"><button onClick={()=>toggle('admin-wilaya-'+wilaya)} className="w-full flex items-center justify-between p-4 text-right hover:bg-gray-50 dark:hover:bg-gray-800"><span><b>📍 ولاية {wilaya}</b><span className="mr-2 text-xs text-gray-500">{courts.length} محكمة إدارية</span></span><span>{open['admin-wilaya-'+wilaya]?'⌃':'⌄'}</span></button>{open['admin-wilaya-'+wilaya]&&<div className="border-t p-3 grid gap-2 md:grid-cols-2">{courts.map(c=><Card key={c.id} i={c} compact/>)}</div>}</div>)}</div>};
 return <div dir="rtl" className="space-y-5">
  <div className="rounded-3xl border border-blue-100 bg-blue-50 p-5"><h2 className="text-lg font-black">📞 دليل الهيئات القضائية ومندوبيات المحامين</h2><p className="mt-2 text-sm leading-7">🤝 هذا العمل مبادرة مستقلة واجتهاد جماعي من زملاء محامين، ولا يتبع وزارة العدل أو أي جهة قضائية أو نقابية أو مهنية. هدفنا الأساسي هو إبقاء <b>أرقام مندوبيات المحامين À JOUR</b>. إذا كان لديك رقم غير موجود أو وجدت رقمًا خاطئًا، ساهم معنا ليستفيد الجميع.</p><div className="mt-3 flex flex-wrap gap-2">{admin?<><button onClick={async()=>{await fetch('/api/admin/logout',{method:'POST'});setAdmin(false)}} className="rounded-xl bg-gray-800 px-3 py-2 text-xs text-white">خروج المدير</button><button onClick={()=>setEdit({name:'',type:'court',wilaya:'',parentId:'',address:'',website:'',email:'',notes:''})} className="rounded-xl bg-blue-700 px-3 py-2 text-xs text-white">➕ إضافة هيئة</button></>:<button onClick={()=>setLogin(true)} className="rounded-xl border bg-white px-3 py-2 text-xs text-blue-700">🔐 دخول المدير</button>}</div></div>
  <div className="sticky top-0 z-30 rounded-2xl border bg-white/95 p-3 shadow-sm backdrop-blur dark:bg-gray-900/95"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="🔎 ابحث عن هيئة، مجلس، محكمة، ولاية أو رقم مندوبية..." className="w-full rounded-xl border bg-gray-50 p-3 outline-none dark:bg-gray-800"/></div>
  {q&&<div className="text-xs text-gray-500">نتائج البحث: {filtered.length} هيئة</div>}
  <Section title="المحكمة العليا" icon="🏛️" count={supreme.length}>{supreme.map(i=><Card key={i.id} i={i}/>)}</Section>
  <Section title="مجلس الدولة" icon="🏛️" count={state.length}>{state.map(i=><Card key={i.id} i={i}/>)}</Section>
  <Section title="المحاكم الإدارية" icon="⚖️" count={adminCourts.length}><p className="mb-3 text-xs leading-6 text-gray-500">يوجد في قاعدة البيانات <b>{adminCourts.length}</b> محكمة إدارية، أي محكمة إدارية لكل ولاية ممثلة في البيانات. تظهر الآن <b>حسب الولاية</b> حتى تكون كل محكمة واضحة ومباشرة، مع إبقاء تقسيمها حسب محاكم الاستئناف متاحًا أدناه.</p><AdminCourts/><div className="mt-5 border-t pt-4"><h4 className="mb-3 text-sm font-black">⚖️ حسب المحاكم الإدارية للاستئناف</h4><div className="space-y-2">{apps.map(a=>{const kids=adminCourts.filter(c=>c.parent_institution_id===a.id);return <div key={a.id} className="rounded-2xl border bg-white dark:bg-gray-900 overflow-hidden"><button onClick={()=>toggle(a.id)} className="w-full flex items-center justify-between p-4 text-right"><span><b>⚖️ {a.name}</b><span className="mr-2 text-xs text-gray-500">{kids.length} محكمة إدارية</span></span><span>{open[a.id]?'⌃':'⌄'}</span></button>{open[a.id]&&<div className="border-t p-3 grid gap-2 md:grid-cols-2">{kids.map(k=><Card key={k.id} i={k} compact/>)}</div>}</div>})}</div></div></Section>
  <Section title="المحاكم التجارية المتخصصة" icon="💼" count={commercial.length}><div className="grid gap-2 md:grid-cols-2">{commercial.map(i=><Card key={i.id} i={i} compact/>)}</div></Section>
  <Section title="المجالس القضائية والمحاكم التابعة لها" icon="⚖️" count={councils.length}><p className="mb-3 text-xs text-gray-500">اضغط على المجلس لفتح المجلس ثم المحاكم التابعة له. يعتمد التنظيم على دليل الجهات القضائية المنشور من وزارة العدل، مع تحديثات قاعدة البيانات المحلية.</p><div className="space-y-2">{councils.map(c=><Council key={c.id} c={c}/>)}</div></Section>
  {login&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-sm rounded-3xl bg-white p-6"><b>🔐 دخول المدير</b><input autoFocus type="password" value={pass} onChange={e=>setPass(e.target.value)} onKeyDown={e=>e.key==='Enter'&&loginAdmin()} placeholder="كلمة السر" className="mt-4 w-full rounded-xl border p-3"/>{err&&<p className="mt-2 text-sm text-red-600">{err}</p>}<button onClick={loginAdmin} className="mt-3 w-full rounded-xl bg-blue-700 p-3 text-white">دخول</button></div></div>}
  {edit&&<div className="fixed inset-0 z-50 overflow-auto bg-black/50 p-4"><div className="mx-auto mt-8 max-w-xl rounded-3xl bg-white p-6"><b>{edit.id?'✏️ تعديل الهيئة':'➕ إضافة هيئة'}</b><div className="mt-4 grid gap-3"><input value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})} placeholder="اسم الهيئة" className="rounded-xl border p-3"/><select value={edit.type} onChange={e=>setEdit({...edit,type:e.target.value})} className="rounded-xl border p-3">{Object.entries(LABEL).map(([v,l])=><option key={v} value={v}>{l as string}</option>)}</select><input value={edit.wilaya||''} onChange={e=>setEdit({...edit,wilaya:e.target.value})} placeholder="الولاية" className="rounded-xl border p-3"/><input value={edit.address||''} onChange={e=>setEdit({...edit,address:e.target.value})} placeholder="العنوان" className="rounded-xl border p-3"/><input value={edit.email||''} onChange={e=>setEdit({...edit,email:e.target.value})} placeholder="البريد الإلكتروني" className="rounded-xl border p-3"/><input value={edit.website||''} onChange={e=>setEdit({...edit,website:e.target.value})} placeholder="الموقع الرسمي" className="rounded-xl border p-3"/><textarea value={edit.notes||''} onChange={e=>setEdit({...edit,notes:e.target.value})} placeholder="ملاحظات" className="rounded-xl border p-3"/></div><div className="mt-4 flex gap-2"><button onClick={saveI} className="flex-1 rounded-xl bg-blue-700 p-3 text-white">حفظ</button><button onClick={()=>setEdit(null)} className="rounded-xl border px-4">إلغاء</button></div></div></div>}
  {phone&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6"><b>📞 {phone.id?'تعديل':'إضافة'} رقم هاتف المندوبية</b><input autoFocus value={phone.value} onChange={e=>setPhone({...phone,value:e.target.value})} placeholder="0550.00.00.00" className="mt-4 w-full rounded-xl border p-3"/><div className="mt-3 flex gap-2"><button onClick={saveP} className="flex-1 rounded-xl bg-blue-700 p-3 text-white">حفظ</button><button onClick={()=>setPhone(null)} className="rounded-xl border px-4">إلغاء</button></div></div></div>}
 </div>;
}