'use client';
import { useEffect, useMemo, useState } from 'react';
type Decision={id:string;decision_number:string;decision_date:string|null;file_number:string|null;chamber:string|null;subject:string;legal_principle:string|null;summary:string|null;full_text:string;related_articles:string[];keywords:string[];source:string|null};
const norm=(s:string)=>s.normalize('NFD').replace(/[\u064B-\u065F]/g,'').replace(/[إأآا]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').toLowerCase();
const fmt=(d:string|null)=>d?new Intl.DateTimeFormat('ar-DZ',{year:'numeric',month:'long',day:'numeric'}).format(new Date(d)):'التاريخ غير متوفر';
export default function JurisprudenceTab(){
 const [items,setItems]=useState<Decision[]>([]),[q,setQ]=useState(''),[chamber,setChamber]=useState('all'),[year,setYear]=useState('all'),[open,setOpen]=useState<string|null>(null),[loading,setLoading]=useState(true),[admin,setAdmin]=useState(false),[edit,setEdit]=useState<any>(null);
 const load=async()=>{try{const r=await fetch('/api/jurisprudence',{cache:'no-store'});const j=await r.json();setItems(j.data||[])}finally{setLoading(false)}};
 useEffect(()=>{load();fetch('/api/admin/session').then(r=>r.json()).then(j=>setAdmin(!!j.authenticated)).catch(()=>{})},[]);
 const chambers=useMemo(()=>Array.from(new Set(items.map(x=>x.chamber).filter(Boolean) as string[])).sort((a,b)=>a.localeCompare(b,'ar')),[items]);
 const years=useMemo(()=>Array.from(new Set(items.map(x=>x.decision_date?.slice(0,4)).filter(Boolean) as string[])).sort((a,b)=>Number(b)-Number(a)),[items]);
 const filtered=useMemo(()=>{const n=norm(q.trim());return items.filter(x=>{const text=norm([x.decision_number,x.file_number,x.chamber,x.subject,x.legal_principle,x.summary,x.full_text,...(x.keywords||[]),...(x.related_articles||[])].filter(Boolean).join(' '));return(!n||text.includes(n))&&(chamber==='all'||x.chamber===chamber)&&(year==='all'||x.decision_date?.startsWith(year))})},[items,q,chamber,year]);
 const save=async()=>{const payload={...edit,related_articles:String(edit.related_articles||'').split(',').map((x:string)=>x.trim()).filter(Boolean),keywords:String(edit.keywords||'').split(',').map((x:string)=>x.trim()).filter(Boolean)};const r=await fetch('/api/admin/jurisprudence',{method:edit.id?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(r.ok){setEdit(null);load()}else alert('تعذر حفظ الاجتهاد')};
 if(loading)return <div className="py-20 text-center font-bold">⚖️ جاري تحميل قاعدة الاجتهادات...</div>;
 return <div dir="rtl" className="mx-auto max-w-5xl space-y-5">
  <div className="rounded-3xl border border-amber-100 bg-amber-50 p-5 dark:bg-amber-950/20"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-black text-[#1a3a5c] dark:text-[#f0c040]">⚖️ اجتهادات المحكمة العليا</h2><p className="mt-2 text-sm leading-7 text-gray-600 dark:text-gray-300">قاعدة نصية قابلة للبحث والتحديث، تُدار من Supabase بدل تخزين الاجتهادات داخل كود التطبيق.</p></div>{admin&&<button onClick={()=>setEdit({decision_number:'',decision_date:'',file_number:'',chamber:'',subject:'',legal_principle:'',summary:'',full_text:'',related_articles:'',keywords:'',source:'',status:'published'})} className="rounded-xl bg-[#1a3a5c] px-3 py-2 text-xs font-bold text-white">➕ إضافة اجتهاد</button>}</div></div>
  <div className="rounded-2xl border bg-white p-3 shadow-sm dark:bg-gray-900"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="🔎 ابحث في رقم القرار، الموضوع، المبدأ، النص، المادة أو الكلمات المفتاحية..." className="w-full rounded-xl border bg-gray-50 p-3 outline-none dark:bg-gray-800"/><div className="mt-3 flex flex-wrap gap-2"><select value={chamber} onChange={e=>setChamber(e.target.value)} className="rounded-xl border p-2 text-xs"><option value="all">كل الغرف</option>{chambers.map(c=><option key={c}>{c}</option>)}</select><select value={year} onChange={e=>setYear(e.target.value)} className="rounded-xl border p-2 text-xs"><option value="all">كل السنوات</option>{years.map(y=><option key={y}>{y}</option>)}</select><span className="mr-auto self-center text-xs text-gray-500">{filtered.length} اجتهاد</span></div></div>
  <div className="space-y-3">{filtered.map(x=><article key={x.id} className="overflow-hidden rounded-2xl border bg-white shadow-sm dark:bg-gray-900"><button onClick={()=>setOpen(open===x.id?null:x.id)} className="w-full p-4 text-right"><div className="flex items-start justify-between gap-3"><div><h3 className="font-black text-[#1a3a5c] dark:text-[#f0c040]">{x.subject}</h3><div className="mt-1 text-xs text-gray-500">قرار: {x.decision_number} · {x.chamber||'الغرفة غير محددة'} · {fmt(x.decision_date)}</div></div><span>{open===x.id?'⌃':'⌄'}</span></div>{x.legal_principle&&<p className="mt-3 line-clamp-2 text-sm leading-6 text-gray-700 dark:text-gray-300">⚖️ {x.legal_principle}</p>}</button>{open===x.id&&<div className="border-t p-4 space-y-4"><div><b>⚖️ المبدأ القانوني</b><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{x.legal_principle||'غير متوفر'}</p></div><div><b>📖 النص</b><p className="mt-2 whitespace-pre-wrap text-sm leading-7">{x.full_text}</p></div>{x.summary&&<div><b>📝 الملخص</b><p className="mt-2 text-sm leading-7">{x.summary}</p></div>}<div className="flex flex-wrap gap-2 text-xs">{(x.related_articles||[]).map(a=><span key={a} className="rounded-full bg-blue-50 px-2 py-1 text-blue-700">المادة {a}</span>)}{(x.keywords||[]).map(k=><span key={k} className="rounded-full bg-gray-100 px-2 py-1">#{k.replaceAll('_',' ')}</span>)}</div><div className="flex flex-wrap gap-2"><button onClick={()=>navigator.clipboard?.writeText(`${x.subject}\n${x.legal_principle||''}\n${x.full_text}`)} className="rounded-xl border px-3 py-2 text-xs">📋 نسخ</button><button onClick={()=>window.open('https://wa.me/?text='+encodeURIComponent(x.subject+'\n'+(x.legal_principle||'')+'\n'+x.full_text),'_blank')} className="rounded-xl bg-green-600 px-3 py-2 text-xs text-white">📲 مشاركة</button>{admin&&<><button onClick={()=>setEdit({...x,related_articles:(x.related_articles||[]).join(', '),keywords:(x.keywords||[]).join(', ')})} className="rounded-xl border px-3 py-2 text-xs">✏️ تعديل</button><button onClick={async()=>{if(confirm('حذف هذا الاجتهاد؟')){await fetch('/api/admin/jurisprudence',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:x.id})});load()}}} className="rounded-xl border px-3 py-2 text-xs text-red-600">🗑️ حذف</button></>}</div>{x.source&&<p className="text-[11px] text-gray-500">المصدر: {x.source}</p>}</div>}</article>)}</div>
  {filtered.length===0&&<div className="rounded-2xl border p-10 text-center text-gray-500">لا توجد نتائج مطابقة.</div>}
  {edit&&<div className="fixed inset-0 z-50 overflow-auto bg-black/50 p-4"><div className="mx-auto mt-8 max-w-2xl rounded-3xl bg-white p-6"><h3 className="font-black">{edit.id?'✏️ تعديل اجتهاد':'➕ إضافة اجتهاد'}</h3><div className="mt-4 grid gap-3"><input value={edit.decision_number} onChange={e=>setEdit({...edit,decision_number:e.target.value})} placeholder="رقم القرار" className="rounded-xl border p-3"/><input type="date" value={edit.decision_date||''} onChange={e=>setEdit({...edit,decision_date:e.target.value})} className="rounded-xl border p-3"/><input value={edit.file_number||''} onChange={e=>setEdit({...edit,file_number:e.target.value})} placeholder="رقم الملف" className="rounded-xl border p-3"/><input value={edit.chamber||''} onChange={e=>setEdit({...edit,chamber:e.target.value})} placeholder="الغرفة" className="rounded-xl border p-3"/><input value={edit.subject} onChange={e=>setEdit({...edit,subject:e.target.value})} placeholder="الموضوع" className="rounded-xl border p-3"/><textarea value={edit.legal_principle||''} onChange={e=>setEdit({...edit,legal_principle:e.target.value})} placeholder="المبدأ القانوني" className="min-h-24 rounded-xl border p-3"/><textarea value={edit.summary||''} onChange={e=>setEdit({...edit,summary:e.target.value})} placeholder="الملخص" className="min-h-24 rounded-xl border p-3"/><textarea value={edit.full_text} onChange={e=>setEdit({...edit,full_text:e.target.value})} placeholder="النص" className="min-h-48 rounded-xl border p-3"/><input value={edit.related_articles||''} onChange={e=>setEdit({...edit,related_articles:e.target.value})} placeholder="المواد: 333, 334" className="rounded-xl border p-3"/><input value={edit.keywords||''} onChange={e=>setEdit({...edit,keywords:e.target.value})} placeholder="الكلمات المفتاحية: نفقة, حضانة" className="rounded-xl border p-3"/><input value={edit.source||''} onChange={e=>setEdit({...edit,source:e.target.value})} placeholder="المصدر" className="rounded-xl border p-3"/></div><div className="mt-4 flex gap-2"><button onClick={save} className="flex-1 rounded-xl bg-[#1a3a5c] p-3 text-white">حفظ</button><button onClick={()=>setEdit(null)} className="rounded-xl border px-4">إلغاء</button></div></div></div>}
 </div>;
}
